# Generated by Django 3.1.7 on 2021-04-10 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PasswordManager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwords',
            name='phoneNo',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
    ]
